apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
    repoURL: https://github.com/abinet/CICD-Demo-Deployment.git
    revision: add-config
    directories:
    - path: apps/*/envs/dev   
  template:    
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'   
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/abinet/CICD-Demo-Deployment.git
        targetRevision: add-config
        path: '{{.path.path}}/helm'
        helm:
          valueFiles:
          - {{.path.path}}/envs/dev/values-dev.yaml
      # Destination cluster and namespace to deploy the application
      destination:
        server: '{{index .path.segments 3}}-cluster'
        namespace: '{{index .path.segments 1}}'